# Generated by Django 3.0.5 on 2020-05-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='vote_cnt',
            field=models.IntegerField(default=0, verbose_name='vote count'),
        ),
    ]
